### ISSUE TITLE
Create a new branch(dev) from main.

### ISSUE THREAD

**Issue by Vignaraj-pai** [Vignaraj-pai/BrowseNGrab#6]
# Create a new branch(dev) from main

- Remove the debian structure and keep only the script files. i.e : 
    - bookmarks.sh - (This contains the NITK-NET script as well) 
    - script.py

**Comment by Abhay-Lejith** [comment]
I'll get it done by evening today.

**Comment by Vignaraj-pai** [comment]
Great!. Get it done as quickly as possible please.
Cause the other issues need this new branch.

**Comment by Abhay-Lejith** [comment]
It's done
