### ISSUE TITLE
Add a feature to specify folder to store the bookmarks.

### ISSUE THREAD

**Issue by Vignaraj-pai** [Vignaraj-pai/BrowseNGrab#8]
# Feature to specify folder to store the bookmarks.

- Currently specifying `-f` gets all the bookmarks of the Firefox browser.
- Change this to something else ( `-ff` ? )
- Add a feature to mention `-f` and then specify the path to a folder
- This folder is where the bookmarks will be stored.

(Keep in mind, right now to collect bookmarks you have to mention `-b` , so you will have to add the `-f folder_name` after the `-b` flag. )

**Comment by NR55** [comment]
Hey, I, Nandan, would like to try to resolve this.

**Comment by Vignaraj-pai** [comment]
# Great. I've assigned this issue to you. 
### Abhay needs to create a new branch. But if you are free then create a new branch (look at the new branch issue I created) and comment that you have fixed that issue.
- The faster this gets done, the better

**Comment by NR55** [comment]
I've added the -f feature to the Bash script. It prints an invalid path statement and proceeds with saving the bookmarks.md and the bookmarks.html file in the pre-defined location, i.e., in ~/Documents/BrowseNGrab.
